default["temp"]["directory"] = "/tmp"
default["software"]["multichain"] = "multichain-1.0.5.tar.gz"
default["blockchain"]["name"] = "chain1"
default["blockchain"]["ip"] = "172.28.128.1"
default["blockchain"]["port"] = "2679"
